#!/bin/sh
mkdir -p "$CI_WORKSPACE/App/Config"
SECRETS_FILE="$CI_WORKSPACE/Configs/secrets.xcconfig"
echo "SENTRY_DSN_URL = ${SENTRY_DSN_URL}" > $SECRETS_FILE
echo "SENTRY_DSN_SCHEME = ${SENTRY_DSN_SCHEME}" >> $SECRETS_FILE
echo "API_BASE_URL = ${API_BASE_URL}" >> $SECRETS_FILE
echo "FIREBASE_GOOGLE_APP_ID = ${FIREBASE_GOOGLE_APP_ID}" >> $SECRETS_FILE
echo "FIREBASE_GCM_SENDER_ID = ${FIREBASE_GCM_SENDER_ID}" >> $SECRETS_FILE
echo "FIREBASE_CLIENT_ID = ${FIREBASE_CLIENT_ID}" >> $SECRETS_FILE
echo "FIREBASE_API_KEY = ${FIREBASE_API_KEY}" >> $SECRETS_FILE
echo "FIREBASE_BUNDLE_ID = ${FIREBASE_BUNDLE_ID}" >> $SECRETS_FILE
echo "FIREBASE_PROJECT_ID = ${FIREBASE_PROJECT_ID}" >> $SECRETS_FILE
echo "FIREBASE_STORAGE_BUCKET = ${FIREBASE_STORAGE_BUCKET}" >> $SECRETS_FILE
